### ISSUE TITLE
start :8000 success but error : no such table security_role

### ISSUE THREAD

**Issue by j2p0** [fbsamples/marketing-api-samples#1]
start :8000 success but error : no such table security_role
im using sqlite3

**Comment by phzhou** [comment]
Hi @japonikaa did you try to run 
`python manage.py migrate` 
while working in the project virtual env?

**Comment by phzhou** [comment]
Hi @japonikaa the issue should be fixed with the latest commit. Please get the latest and run `python manage.py migrate` then `python manage.py runsslserver`. Let me know if the issue remains.
