### ISSUE TITLE
Where is targeting.py sample code?

### ISSUE THREAD

**Issue by yoolbinum** [fbsamples/marketing-api-samples#4]
https://github.com/fbsamples/marketing-api-samples/blob/master/samples/samplecode/targeting.py

Only this sample code is empty. Please upload this file

**Comment by phzhou** [comment]
Hi @uyb6711 ! 
The targeting.py file is used as a placeholder for the Targeting Spec sample, required by the Django app.
The purpose of the sample is to show case the targeting spec setting dialog, which you can see in this JavaScript component:

https://github.com/fbsamples/marketing-api-samples/blob/master/components/js_src/targeting_composer.jsx
